### ISSUE TITLE
Getting an error that a SchwabenCode file can't be located when installing DNN Reports

### ISSUE THREAD

**Issue by PostalMike** [SchwabenCode/QuickIO#18]
Here is what I'm seeing, here is the error about halfway down.  My email is mdurthaler@sbcglobal.net.

The Reports module will install on DNN 7 / 8 with no issues.

**SchwabenCode.QuickIO.PathNotFoundException: The system cannot find the file specified.<-- here it is.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)**

2018-05-29 15:48:25,260 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - Reading files
2018-05-29 15:48:25,274 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\.gitattributes read successfully
2018-05-29 15:48:25,276 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\.gitignore read successfully
2018-05-29 15:48:25,285 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/.references\DotNetNuke.WebUtility.dll read successfully
2018-05-29 15:48:25,327 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/.references\DotNetNuke.dll read successfully
2018-05-29 15:48:25,329 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/.references\Microsoft.ApplicationBlocks.Data.dll read successfully
2018-05-29 15:48:25,372 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/App_LocalResources\Packages.ascx.resx read successfully
2018-05-29 15:48:25,378 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/App_LocalResources\Settings.ascx.resx read successfully
2018-05-29 15:48:25,383 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/App_LocalResources\SharedResources.resx read successfully
2018-05-29 15:48:25,390 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/App_LocalResources\ViewReports.ascx.resx read successfully
2018-05-29 15:48:25,397 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/BuildSupport\DotNetNuke.Common.targets read successfully
2018-05-29 15:48:25,405 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/BuildSupport\ICSharpCode.SharpZipLib.dll read successfully
2018-05-29 15:48:25,409 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/BuildSupport\MSBuild.Community.Tasks.Targets read successfully
2018-05-29 15:48:25,418 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/BuildSupport\MSBuild.Community.Tasks.dll read successfully
2018-05-29 15:48:25,424 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Converters\ConverterInstanceInfo.vb read successfully
2018-05-29 15:48:25,427 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Converters\ConvertingDataReader.vb read successfully
2018-05-29 15:48:25,430 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Data\DataProvider.vb read successfully
2018-05-29 15:48:25,433 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Data\SqlDataProvider.vb read successfully
2018-05-29 15:48:25,436 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources/ADO\GenericADODataSource.vb read successfully
2018-05-29 15:48:25,439 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources\ADODataSourceBase.vb read successfully
2018-05-29 15:48:25,441 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources\DataSourceBase.vb read successfully
2018-05-29 15:48:25,443 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources/DotNetNuke\DotNetNukeDataSource.vb read successfully
2018-05-29 15:48:25,491 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources\IDataSource.vb read successfully
2018-05-29 15:48:25,497 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources\IDataSourceSettingsControl.vb read successfully
2018-05-29 15:48:25,503 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources\SqlDataSourceBase.vb read successfully
2018-05-29 15:48:25,512 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/DataSources/SqlServer\SqlServerDataSource.vb read successfully
2018-05-29 15:48:25,519 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Exceptions\DataSourceException.vb read successfully
2018-05-29 15:48:25,523 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Exceptions\DataSourceNotConfiguredException.vb read successfully
2018-05-29 15:48:25,527 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Exceptions\LocalizedText.vb read successfully
2018-05-29 15:48:25,530 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Exceptions\ReportsModuleException.vb read successfully
2018-05-29 15:48:25,534 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Exceptions\RequiredSettingMissingException.vb read successfully
2018-05-29 15:48:25,538 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Exceptions\VisualizerException.vb read successfully
2018-05-29 15:48:25,543 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\ExtensionContext.vb read successfully
2018-05-29 15:48:25,546 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\ExtensionType.vb read successfully
2018-05-29 15:48:25,549 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\IReportsControl.vb read successfully
2018-05-29 15:48:25,553 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\IReportsExtension.vb read successfully
2018-05-29 15:48:25,557 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\IReportsSettingsControl.vb read successfully
2018-05-29 15:48:25,561 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\ReportsControlBase.vb read successfully
2018-05-29 15:48:25,564 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\ReportsExtensionBase.vb read successfully
2018-05-29 15:48:25,567 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Extensions\ReportsSettingsBase.vb read successfully
2018-05-29 15:48:25,571 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components\ReportInfo.vb read successfully
2018-05-29 15:48:25,575 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components\ReportsClientAPI.vb read successfully
2018-05-29 15:48:25,580 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components\ReportsController.vb read successfully
2018-05-29 15:48:25,583 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components\Utilities.vb read successfully
2018-05-29 15:48:25,585 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Visualizers\IVisualizerControl.vb read successfully
2018-05-29 15:48:25,588 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Components/Visualizers\VisualizerControlBase.vb read successfully
2018-05-29 15:48:25,591 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Controls/App_LocalResources\SqlDataSourceCommonSettingsControl.ascx.resx read successfully
2018-05-29 15:48:25,593 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Controls\SettingsFormControl.vb read successfully
2018-05-29 15:48:25,594 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Controls\SqlDataSourceCommonSettingsControl.ascx read successfully
2018-05-29 15:48:25,596 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Controls\SqlDataSourceCommonSettingsControl.ascx.designer.vb read successfully
2018-05-29 15:48:25,598 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Controls\SqlDataSourceCommonSettingsControl.ascx.vb read successfully
2018-05-29 15:48:25,602 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/ADO/App_LocalResources\DataSource.ascx.resx read successfully
2018-05-29 15:48:25,604 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/ADO/App_LocalResources\Settings.ascx.resx read successfully
2018-05-29 15:48:25,607 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/ADO\Settings.ascx read successfully
2018-05-29 15:48:25,609 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/ADO\Settings.ascx.designer.vb read successfully
2018-05-29 15:48:25,610 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/ADO\Settings.ascx.vb read successfully
2018-05-29 15:48:25,613 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/DotNetNuke/App_LocalResources\DataSource.ascx.resx read successfully
2018-05-29 15:48:25,614 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/DotNetNuke\Settings.ascx read successfully
2018-05-29 15:48:25,616 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/DotNetNuke\Settings.ascx.designer.vb read successfully
2018-05-29 15:48:25,618 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/DotNetNuke\Settings.ascx.vb read successfully
2018-05-29 15:48:25,621 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/SqlServer/App_LocalResources\DataSource.ascx.resx read successfully
2018-05-29 15:48:25,624 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/SqlServer/App_LocalResources\Settings.ascx.resx read successfully
2018-05-29 15:48:25,626 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/SqlServer\Settings.ascx read successfully
2018-05-29 15:48:25,627 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/SqlServer\Settings.ascx.designer.vb read successfully
2018-05-29 15:48:25,629 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/DataSources/SqlServer\Settings.ascx.vb read successfully
2018-05-29 15:48:25,655 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Documentation\Reports_05_07_01_User_Manual.docx read successfully
2018-05-29 15:48:25,658 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Install/Scripts\04.04.02.SqlDataProvider read successfully
2018-05-29 15:48:25,660 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Install/Scripts\04.05.00.SqlDataProvider read successfully
2018-05-29 15:48:25,662 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Install/Scripts\05.00.00.SqlDataProvider read successfully
2018-05-29 15:48:25,664 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Install/Scripts\05.01.00.SqlDataProvider read successfully
2018-05-29 15:48:25,666 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Install/Scripts\05.05.00.SqlDataProvider read successfully
2018-05-29 15:48:25,669 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Install/Scripts\Uninstall.SqlDataProvider read successfully
2018-05-29 15:48:25,671 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\LICENSE read successfully
2018-05-29 15:48:25,674 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/My Project\AssemblyInfo.vb read successfully
2018-05-29 15:48:25,676 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Packages.ascx read successfully
2018-05-29 15:48:25,678 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Packages.ascx.designer.vb read successfully
2018-05-29 15:48:25,680 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Packages.ascx.vb read successfully
2018-05-29 15:48:25,682 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\README.md read successfully
2018-05-29 15:48:25,685 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Reports.dnn read successfully
2018-05-29 15:48:25,687 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Reports.sln read successfully
2018-05-29 15:48:25,689 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Reports.vbproj read successfully
2018-05-29 15:48:25,692 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Settings.ascx read successfully
2018-05-29 15:48:25,694 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Settings.ascx.designer.vb read successfully
2018-05-29 15:48:25,696 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Settings.ascx.vb read successfully
2018-05-29 15:48:25,698 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\Settings_generated_.vb read successfully
2018-05-29 15:48:25,700 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\ViewReports.ascx read successfully
2018-05-29 15:48:25,702 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\ViewReports.ascx.designer.vb read successfully
2018-05-29 15:48:25,705 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\ViewReports.ascx.vb read successfully
2018-05-29 15:48:25,709 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid/App_LocalResources\Settings.ascx.resx read successfully
2018-05-29 15:48:25,711 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid/App_LocalResources\Visualizer.ascx.resx read successfully
2018-05-29 15:48:25,713 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid\Settings.ascx read successfully
2018-05-29 15:48:25,715 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid\Settings.ascx.designer.vb read successfully
2018-05-29 15:48:25,717 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid\Settings.ascx.vb read successfully
2018-05-29 15:48:25,719 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid\Visualizer.ascx read successfully
2018-05-29 15:48:25,722 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid\Visualizer.ascx.designer.vb read successfully
2018-05-29 15:48:25,725 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/Grid\Visualizer.ascx.vb read successfully
2018-05-29 15:48:25,728 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML/App_LocalResources\Settings.ascx.resx read successfully
2018-05-29 15:48:25,730 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML/App_LocalResources\Visualizer.ascx.resx read successfully
2018-05-29 15:48:25,732 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML\Settings.ascx read successfully
2018-05-29 15:48:25,734 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML\Settings.ascx.designer.vb read successfully
2018-05-29 15:48:25,737 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML\Settings.ascx.vb read successfully
2018-05-29 15:48:25,739 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML\Visualizer.ascx read successfully
2018-05-29 15:48:25,741 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML\Visualizer.ascx.designer.vb read successfully
2018-05-29 15:48:25,742 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/HTML\Visualizer.ascx.vb read successfully
2018-05-29 15:48:25,745 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT/App_LocalResources\Settings.ascx.resx read successfully
2018-05-29 15:48:25,747 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT/App_LocalResources\Visualizer.ascx.resx read successfully
2018-05-29 15:48:25,749 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\ExtensionObjectInfo.vb read successfully
2018-05-29 15:48:25,751 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\IXsltExtensionObject.vb read successfully
2018-05-29 15:48:25,754 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\Settings.ascx read successfully
2018-05-29 15:48:25,756 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\Settings.ascx.designer.vb read successfully
2018-05-29 15:48:25,759 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\Settings.ascx.vb read successfully
2018-05-29 15:48:25,760 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\Visualizer.ascx read successfully
2018-05-29 15:48:25,762 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\Visualizer.ascx.designer.vb read successfully
2018-05-29 15:48:25,764 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/Visualizers/XSLT\Visualizer.ascx.vb read successfully
2018-05-29 15:48:25,767 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/images\BuiltInPackage.gif read successfully
2018-05-29 15:48:25,769 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/images\LegacyPackage.gif read successfully
2018-05-29 15:48:25,771 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/images\ManagePackages.gif read successfully
2018-05-29 15:48:25,774 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00/js\dnn.reports.js read successfully
2018-05-29 15:48:25,776 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\license.txt read successfully
2018-05-29 15:48:25,778 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\module.css read successfully
2018-05-29 15:48:25,779 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - File DNN.Reports-Release_05.08.00\releaseNotes.txt read successfully
2018-05-29 15:48:25,780 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - Reading files done.
2018-05-29 15:48:25,781 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - Reading Installation Manifest file
2018-05-29 15:48:25,792 [DESKTOP-2EBCEEN][Thread:103][INFO] DotNetNuke.Services.Installer.Log.Logger - Reading Package Manifest - Module - DNN_Reports
2018-05-29 15:48:25,804 [DESKTOP-2EBCEEN][Thread:103][TRACE] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - Dumping all Application Errors
2018-05-29 15:48:25,805 [DESKTOP-2EBCEEN][Thread:103][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - SchwabenCode.QuickIO.PathNotFoundException: The system cannot find the file specified.<-- here it is.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at Dnn.PersonaBar.Extensions.Components.InstallController.GetInstaller(Stream stream, String fileName, Int32 portalId, String legacySkin)
   at Dnn.PersonaBar.Extensions.Components.InstallController.ParsePackage(PortalSettings portalSettings, UserInfo user, String filePath, Stream stream)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.<>c__DisplayClass39_1.<UploadFileAction>b__1(Object <state>)
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
2018-05-29 15:48:25,807 [DESKTOP-2EBCEEN][Thread:103][TRACE] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - End Dumping all Application Errors

**Comment by BenjaminAbt** [comment]
Maybe you should ask the Report Module developer then....? ;-)
This is just an independent library. I do not have any relations to DotNetNuke, sorry.
